CREATE DATABASE project; USE project;
CREATE TABLE todo(
   id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
   title VARCHAR(255) NOT NULL, 
   status TINYINT(4) DEFAULT 0 NOT NULL,
   family_id INTEGER UNSIGNED NOT NULL,
   user_id INTEGER UNSIGNED NOT NULL,
   time DATETIME DEFAULT NULL
   );
